
report.customfields.environment=Default
report.customfields.user=User
report.customfields.squad=Benefit
serenity.requirement.types=Epics,Features
serenity.requirements.dir=src/test/resources
serenity.console.colors=true
serenity.include.actor.name.in.consequences=true
json.pretty.printing=true
report.assets.directory=src/test/resources/asset
serenity.reports.show.step.details=true

